stages:
- test
- analyze
- build
- publish

#############
# Templates #
#############
.job: &job
  before_script:
  - ./.gitlab-ci/$CI_JOB_STAGE/$CI_JOB_NAME.sh setup
  dependencies: []
  script:
  - ./.gitlab-ci/$CI_JOB_STAGE/$CI_JOB_NAME.sh

.dind: &dind
  <<: *job
  tags:
  - dind
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  services:
  - docker:stable-dind

#######
# Tests
#######
.dispatcher: &dispatcher
  <<: *job
  stage: test
  image: hub.lavasoftware.org/lava/ci-images/$CI_JOB_NAME
  artifacts:
    reports:
      junit: dispatcher.xml

.server: &server
  <<: *job
  stage: test
  image: hub.lavasoftware.org/lava/ci-images/$CI_JOB_NAME
  artifacts:
    reports:
      junit:
      - common.xml
      - server.xml

dispatcher-debian-9: *dispatcher
server-debian-9: *server
dispatcher-debian-10: *dispatcher
server-debian-10: *server

###########
# Analyze #
###########
black:
  <<: *job
  stage: analyze
  image: debian:buster

codestyle:
  <<: *job
  stage: analyze
  image: debian:9

coverage:
  <<: *job
  stage: analyze
  image: hub.lavasoftware.org/lava/ci-images/server-debian-9
  coverage: '/^TOTAL.+ (\d+\.\d+)%$/'
  artifacts:
    paths:
    - htmlcov

sast:
  <<: *dind
  stage: analyze
  allow_failure: true
  artifacts:
    paths: [gl-sast-report.json]

#########
# Build #
#########
doc:
  <<: *job
  stage: build
  image: debian:9
  artifacts:
    paths:
    - doc/v2/_build/html

debian-pkg:
  <<: *job
  stage: build
  image: hub.lavasoftware.org/lava/ci-images/debian-9-packaging
  artifacts:
    paths:
    - build/*.deb

###########
# Publish #
###########
.publish: &publish
  <<: *dind
  stage: publish
  dependencies: [debian-pkg]
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE/$CI_JOB_NAME

lava-dispatcher: *publish
lava-server: *publish
