.job: &job
  image: docker:stable
  before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - apk add git python3 py3-jinja2 py3-yaml
  script:
#  - ./share/generate.py
#  - '[ -n "$(git diff)" ] && exit 1 || :'
  - docker build -t $IMAGE_TAG $CI_JOB_NAME
  - 'docker run --rm --volume "$PWD/$CI_JOB_NAME/test.sh":/root/test.sh $IMAGE_TAG /root/test.sh'
  - '[ "$CI_COMMIT_REF_NAME" = "master" ] && docker push $IMAGE_TAG || :'
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    IMAGE_TAG: $CI_REGISTRY_IMAGE/$CI_JOB_NAME

.aarch64: &aarch64
  <<: *job
  tags: [aarch64, dind]

.amd64: &amd64
  <<: *job
  tags: [amd64, dind]

aarch64/lava-dispatcher-base: *aarch64
aarch64/lava-server-base: *aarch64
amd64/lava-dispatcher-base: *amd64
amd64/lava-server-base: *amd64
