stages:
- test
- analyze
- build
- docker
- deploy

include:
  template: SAST.gitlab-ci.yml

###########################
# Templates               #
#                         #
# make sure all jobs use  #
# architecture tags.      #
###########################
.job: &job
  before_script:
  - ./.gitlab-ci/$CI_JOB_STAGE/$CI_JOB_NAME.sh setup
  dependencies: []
  except: [schedules]
  tags:
  - amd64
  script:
  - ./.gitlab-ci/$CI_JOB_STAGE/$CI_JOB_NAME.sh

.job_aarch64: &job_aarch64
  <<: *job
  tags:
  - aarch64

.dind: &dind
  <<: *job
  tags:
  - amd64-dind
  image: docker:18.09.9-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_BUILDKIT: 1
  services:
  - docker:18.09.9-dind

#######
# Tests
#######
.dispatcher: &dispatcher
  <<: *job
  stage: test
  image: hub.lavasoftware.org/lava/ci-images/amd64/$CI_JOB_NAME
  artifacts:
    reports:
      junit: dispatcher.xml

.server: &server
  <<: *job
  stage: test
  image: hub.lavasoftware.org/lava/ci-images/amd64/$CI_JOB_NAME
  artifacts:
    reports:
      junit:
      - common.xml
      - server.xml

dispatcher-debian-9: *dispatcher
server-debian-9: *server
dispatcher-debian-10: *dispatcher
server-debian-10: *server
dispatcher-debian-11: *dispatcher
server-debian-11: *server

###########
# Analyze #
###########
.analyze: &analyze
  <<: *job
  image: hub.lavasoftware.org/lava/ci-images/amd64/analyze
  stage: analyze
  except:
    refs:
    - tags

black:
  <<: *analyze

code_quality:
  <<: *analyze
  artifacts:
    reports:
      codequality: gl-code-quality-report.json

coverage:
  <<: *analyze
  image: hub.lavasoftware.org/lava/ci-images/amd64/server-debian-10
  coverage: '/^TOTAL.+ (\d+\.\d+)%$/'
  artifacts:
    paths:
    - htmlcov

dockerfiles:
  <<: *analyze

job-schema:
  <<: *analyze

pylint:
  <<: *analyze

sast:
  stage: analyze
  tags:
  - amd64-dind
  variables:
    SAST_DEFAULT_ANALYZERS: "bandit"

#########
# Build #
#########
doc:
  <<: *job
  stage: build
  image: debian:9
  artifacts:
    paths:
    - doc/v2/_build/html

amd64/pkg-debian-9:
  <<: *job
  stage: build
  except: []
  image: hub.lavasoftware.org/lava/ci-images/amd64/pkg-debian-9
  artifacts:
    paths:
    - _build/*.deb
    # handle native package - need to publish the source
    - _build/*.tar.xz
    - _build/*.dsc
    - _build/*.changes
    - _build/*.buildinfo

amd64/pkg-debian-10:
  <<: *job
  stage: build
  except: []
  image: hub.lavasoftware.org/lava/ci-images/amd64/pkg-debian-10
  artifacts:
    paths:
    - _build/*.deb
    # handle native package - need to publish the source
    - _build/*.tar.xz
    - _build/*.dsc
    - _build/*.changes
    - _build/*.buildinfo

##########
# Docker #
##########
.docker: &docker
  <<: *dind
  stage: docker
  dependencies: [amd64/pkg-debian-10]
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/$CI_JOB_NAME

.docker_aarch64: &docker_aarch64
  <<: *docker
  only:
    refs:
    - master
    - tags
  tags: [aarch64-dind]
  dependencies: [amd64/pkg-debian-10]

amd64/lava-dispatcher: *docker
amd64/lava-server: *docker
aarch64/lava-dispatcher: *docker_aarch64
aarch64/lava-server: *docker_aarch64

##########
# Deploy #
##########

lavafed-master:
  <<: *job
  stage: deploy
  tags: [deploy]
  except: []
  only: [schedules]
  environment:
    name: lavafed-master
    url: https://federation.lavasoftware.org/lava/

reprepro-master:
  <<: *job
  stage: deploy
  # Environments and therefore runners are tied to
  # a specific branch. You'll see this message:
  # "This job is creating a deployment to reprepro-master and
  # will overwrite the latest deployment."
  tags: [deploy]
  dependencies:
  - amd64/pkg-debian-9
  - amd64/pkg-debian-10
  except: []
  only: [schedules]
  environment:
    name: reprepro-master
    url: https://apt.lavasoftware.org

reprepro-release:
  <<: *job
  stage: deploy
  # Environments and therefore runners are tied to
  # a specific branch. You'll see this message:
  # "This job is creating a deployment to reprepro-release and
  # will overwrite the latest deployment."
  tags: [deploy]
  only:
    refs:
    - tags
  dependencies:
  - amd64/pkg-debian-9
  - amd64/pkg-debian-10
  except: [schedules]
  environment:
    name: reprepro-release
    url: https://apt.lavasoftware.org

doc-deploy:
  stage: deploy
  tags: [deploy]
  only:
    refs:
    - tags
  dependencies:
  - doc
  script:
  - mkdir -p ${HOME}/docs/lava
  - rsync -av --delete doc/v2/_build/html ${HOME}/docs/lava/
  environment:
    name: documentation
    url: https://docs.lavasoftware.org/lava/
