.job: &job
  before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  image: docker:stable
  tags:
  - dind
  script:
  - docker build -t $IMAGE_TAG $CI_JOB_NAME
  - '[ "$CI_COMMIT_REF_NAME" = "master" ] && docker push $IMAGE_TAG || :'
  services:
    - docker:dind
  stage: build
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    IMAGE_TAG: $CI_REGISTRY_IMAGE/$CI_JOB_NAME

lava-dispatcher-base: *job
lava-server-base: *job
