stages:
- short
- full
- analysis
- packaging

# template jobs
.dispatcher: &dispatcher
  stage: full
  image: hub.lavasoftware.org/lava/ci-images/$CI_JOB_NAME
  script:
  - PYTHONPATH=. py.test-3 --cache-clear -v lava_dispatcher/test

.server: &server
  stage: full
  image: hub.lavasoftware.org/lava/ci-images/$CI_JOB_NAME
  script:
  - PYTHONPATH=. py.test-3 --cache-clear --ds lava_server.settings.development -v lava_scheduler_app/tests lava_results_app/tests linaro_django_xmlrpc/tests.py
  - PYTHONPATH=. py.test-3 --cache-clear -v lava_common/test

# quicktest
codestyle:
  stage: short
  image: debian:9
  before_script:
  - apt-get update -qq
  - apt-get install --no-install-recommends -y pycodestyle
  script:
  - pycodestyle --ignore E501,E203,W503 .

dispatcher-debian-9:
  <<: *dispatcher
  stage: short

server-debian-9:
  <<: *server
  stage: short

# Full test suite
dispatcher-debian-10: *dispatcher
server-debian-10: *server

# coverage
coverage:
  stage: analysis
  image: hub.lavasoftware.org/lava/ci-images/server-debian-10
  before_script:
  - apt-get install --no-install-recommends -y python3-pytest python3-pytest-cov
  coverage: '/^TOTAL.+ (\d+\.\d+)%$/'
  script:
  - PYTHONPATH=. py.test-3 --cache-clear -v --cov --cov-report= lava_dispatcher/test
  - PYTHONPATH=. py.test-3 --cache-clear -v --ds lava_server.settings.development --cov --cov-append --cov-report= lava_scheduler_app/tests lava_results_app/tests linaro_django_xmlrpc/tests.py
  - PYTHONPATH=. py.test-3 --cache-clear -v --cov --cov-append --cov-report=term --cov-report=html lava_common/test
  artifacts:
    paths:
    - htmlcov

# static analysis with bandit
# Integrated only in GitLab EE (with some format changes)
sast:
  stage: analysis
  image: debian:buster
  before_script:
  - apt-get update -qq
  - apt-get install --no-install-recommends -y python3-bandit
  script:
  - bandit -a vuln -f json -x lava_common/test,lava_dispatcher/test,lava_results_app/tests,lava_scheduler_app/tests -r . -o gl-sast-report.json || true
  artifacts:
    paths: [gl-sast-report.json]

# prospector check
prospector:
  stage: analysis
  image: debian:buster
  before_script:
  - apt-get update -qq
  - apt-get install --no-install-recommends -y python3-pip python3-setuptools
  - pip3 install prospector
  script:
  - prospector -o json . > gl-prospector.json || true
  artifacts:
    paths: [gl-prospector.json]

# Build the doc
doc:
  stage: packaging
  image: debian:9
  before_script:
  - apt-get update -qq
  - apt-get install --no-install-recommends -y git make python3 python3-sphinx python3-sphinx-bootstrap-theme
  script:
  - make -C doc/v2 html
  artifacts:
    paths:
    - doc/v2/_build/html

debian-pkg:
  stage: packaging
  image: hub.lavasoftware.org/lava/ci-images/server-debian-9
  before_script:
  - DEBIAN_FRONTEND=noninteractive apt-get install -y devscripts debhelper node-uglify python3-sphinx python3-sphinx-bootstrap-theme
  script:
  - ./share/debian-dev-build.sh -p lava -a amd64 -b master -o build
