lava-base:
  before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  image: docker:stable
  tags:
  - dind
  script:
  - docker build -t $DISPATCHER_TAG --target lava-dispatcher-base lava-base
  - docker build -t $SERVER_TAG --target lava-server-base lava-base
  - '[ "$CI_COMMIT_REF_NAME" = "master" ] && docker push $DISPATCHER_TAG || :'
  - '[ "$CI_COMMIT_REF_NAME" = "master" ] && docker push $SERVER_TAG || :'
  services:
    - docker:dind
  stage: build
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DISPATCHER_TAG: $CI_REGISTRY_IMAGE/lava-dispatcher-base
    SERVER_TAG: $CI_REGISTRY_IMAGE/lava-server-base
